#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSIONS="${DAIANA_MIGRATION_TEST_PG_VERSIONS:-}"

if [ -z "$VERSIONS" ]; then
  printf 'SKIP: set DAIANA_MIGRATION_TEST_PG_VERSIONS="15 17" to run disposable PostgreSQL migration tests\n'
  exit 0
fi

command -v docker >/dev/null 2>&1 || { printf 'FAIL: docker is required\n' >&2; exit 1; }
docker info >/dev/null 2>&1 || { printf 'FAIL: Docker daemon is unavailable\n' >&2; exit 1; }

log() { printf '===> %s\n' "$*" >&2; }
die() { printf 'ERROR: %s\n' "$*" >&2; return 1; }
docker_cmd() { command docker "$@"; }

cd "$ROOT_DIR"
# shellcheck disable=SC1091
source "$ROOT_DIR/utils/daiana-migrations.sh"

for pg_version in $VERSIONS; do
  case "$pg_version" in 15|17) ;; *) die "Unsupported test PostgreSQL version: $pg_version"; exit 1 ;; esac
  container="daiana-migration-test-pg${pg_version}-$$"
  work_dir="$(mktemp -d)"
  cleanup() {
    docker rm -f "$container" >/dev/null 2>&1 || true
    rm -rf "$work_dir"
  }
  trap cleanup EXIT INT TERM

  docker run --rm -d --name "$container" -e POSTGRES_PASSWORD=test-password "postgres:${pg_version}-alpine" >/dev/null
  ready=0
  for _attempt in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30; do
    if docker exec "$container" pg_isready -U postgres >/dev/null 2>&1; then ready=1; break; fi
    sleep 1
  done
  [ "$ready" -eq 1 ] || die "PostgreSQL $pg_version did not become ready"

  docker exec -i -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 <<'SQL'
CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE service_role NOLOGIN;
CREATE SCHEMA private AUTHORIZATION postgres;
CREATE TABLE public.tenants ("idTenant" integer PRIMARY KEY);
CREATE TABLE public.tenant_plans (
  id integer PRIMARY KEY, "idTenant" integer NOT NULL, "planName" text NOT NULL,
  "maxMessages" integer, "studioIntegrated" boolean, "periodStartAt" timestamptz NOT NULL,
  "expiresAt" timestamptz, "validatedAt" timestamptz, status text NOT NULL,
  "createdAt" timestamptz, "updatedAt" timestamptz
);
CREATE TABLE public.aibot ("idBot" integer PRIMARY KEY, "idTenant" integer NOT NULL, botpublic boolean NOT NULL);
CREATE TABLE public.history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idBot" integer NOT NULL, "idUser" integer, message text NOT NULL,
  created text, metadata jsonb, dataframe jsonb, "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT history_message_not_reject CHECK (message <> 'reject')
);
CREATE SCHEMA studio;
CREATE TABLE studio.organization (id uuid PRIMARY KEY);
CREATE TABLE studio.workspace (id uuid PRIMARY KEY, "organizationId" uuid NOT NULL);
INSERT INTO public.tenants VALUES (1);
INSERT INTO public.tenant_plans VALUES (1, 1, 'studio', 100, true, now(), now() + interval '1 year', now(), 'active', now(), now());
INSERT INTO public.aibot VALUES (10, 1, true), (11, 1, false);
INSERT INTO public.history ("idBot", "idUser", message, created) VALUES
  (10, 1, 'public historical', 'bot'), (11, 1, 'private historical', 'bot');
INSERT INTO studio.organization VALUES ('ca2a7ece-14c6-458c-9266-5c3d96e547f2');
INSERT INTO studio.workspace VALUES ('cd469aed-4042-477b-b508-9de39d395056', 'ca2a7ece-14c6-458c-9266-5c3d96e547f2');
SQL

  migration_dir="$work_dir/migrations"
  drift_dir="$work_dir/drift"
  mkdir -p "$migration_dir" "$drift_dir"
  cat > "$work_dir/tenant-secret-schema.sql" <<'SQL'
CREATE EXTENSION IF NOT EXISTS pgcrypto;
ALTER TABLE public.tenants ADD COLUMN settings jsonb;
UPDATE public.tenants
SET settings = '{"created_by":"qa","domain":"example.test"}'
WHERE "idTenant" = 1;
SQL
  docker exec -i -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 < "$work_dir/tenant-secret-schema.sql" >/dev/null
  cp "$ROOT_DIR/volumes/db/daiana-migrations/20260805120000_backfill_tenant_secrets.sql" "$migration_dir/"
  cp "$ROOT_DIR/volumes/db/daiana-migrations/20260717120000_add_shared_message_quota.sql" "$migration_dir/"

  export POSTGRES_PASSWORD=test-password POSTGRES_DB=postgres DAIANA_DB_CONTAINER="$container" DAIANA_MIGRATION_PROFILE=standard
  export DAIANA_MIGRATIONS_DIR="$migration_dir"
  run_daiana_migrations
  switch_dir="$work_dir/profile-switch"
  mkdir -p "$switch_dir"
  printf 'CREATE TABLE public.profile_switch_ddl(id integer);\n' > "$switch_dir/20260901000000_profile_switch_ddl.sql"
  if switch_error="$(POSTGRES_PASSWORD=test-password POSTGRES_DB=postgres DAIANA_DB_CONTAINER="$container" DAIANA_MIGRATIONS_DIR="$switch_dir" DAIANA_MIGRATION_PROFILE=legacy-daianastudio DAIANA_MIGRATION_LEDGER=private.daiana_installer_schema_migrations run_daiana_migrations 2>&1)"; then
    die "PostgreSQL $pg_version legacy profile was accepted after standard migrations"
  fi
  [[ "$switch_error" == *'profile interlock'*'refusing legacy-daianastudio before DDL'* ]] || die "PostgreSQL $pg_version standard-to-legacy interlock error was unclear: $switch_error"
  docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -Atqc \
    "SELECT public.reserve_tenant_message_quota(1, 'pre-replay', 'integration')->>'status'; SELECT public.release_tenant_message_quota(1, 'pre-replay', 'integration');" >/dev/null
  cp "$ROOT_DIR/volumes/db/daiana-migrations/20260725170000_upgrade_shared_message_quota_replay.sql" "$migration_dir/"
  run_daiana_migrations
  run_daiana_migrations

  docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 \
    -c 'BEGIN; SELECT pg_advisory_xact_lock(1480867157, 1296651378); SELECT pg_sleep(3); COMMIT;' >/dev/null &
  lock_pid=$!
  sleep 1
  lock_start="$(date +%s)"
  run_daiana_migrations
  wait "$lock_pid"
  lock_elapsed=$(( $(date +%s) - lock_start ))
  [ "$lock_elapsed" -ge 2 ] || die "PostgreSQL $pg_version runner did not wait for the global advisory lock"

  result="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "
    SELECT count(*) = 3 FROM private.daiana_installer_schema_migrations;
    SELECT EXISTS (SELECT 1 FROM private.daiana_installer_schema_migrations WHERE version = '20260805120000');
    SELECT settings ? 'secretSeed' AND settings ? 'teamsSecret' FROM public.tenants WHERE \"idTenant\" = 1;
    SELECT to_regclass('public.profile_switch_ddl') IS NULL;
    SELECT to_regclass('private.daiana_legacy_daianastudio_schema_migrations') IS NULL;
    SELECT to_regnamespace('studio') IS NOT NULL AND to_regnamespace('daianastudio') IS NULL;
    SELECT checksum = 'a006dd4648b127b2cd2629f1a60364d759c729c9469a2978deb754ae6837c689' FROM private.daiana_installer_schema_migrations WHERE version = '20260717120000';
    SELECT checksum = 'ad89ebdecb3a138be57fcc0535bb73a7569468c7cb518188f4709e1894f1f528' FROM private.daiana_installer_schema_migrations WHERE version = '20260725170000';
    SELECT result->>'legacy' = 'true' FROM public.tenant_message_quota_reservations WHERE \"requestId\" = 'pre-replay' AND source = 'integration';
    SELECT public.resolve_daiana_tenant_from_studio('ca2a7ece-14c6-458c-9266-5c3d96e547f2', 'cd469aed-4042-477b-b508-9de39d395056') = 1;
    SELECT NOT has_table_privilege('anon', 'public.tenant_message_quota_periods', 'SELECT');
    SELECT NOT has_table_privilege('service_role', 'public.tenant_message_quota_periods', 'INSERT');
    SELECT has_table_privilege('service_role', 'public.tenant_message_quota_periods', 'SELECT');
    SELECT has_function_privilege('service_role', 'public.reserve_tenant_message_quota(integer,text,text,timestamptz)', 'EXECUTE');
    SELECT NOT has_function_privilege('authenticated', 'public.reserve_tenant_message_quota(integer,text,text,timestamptz)', 'EXECUTE');
    SELECT has_function_privilege('service_role', 'public.finalize_tenant_message_quota_turn(text,text,jsonb,timestamptz)', 'EXECUTE');
    SELECT NOT has_function_privilege('authenticated', 'public.finalize_tenant_message_quota_turn(text,text,jsonb,timestamptz)', 'EXECUTE');
    SELECT has_function_privilege('service_role', 'public.reserve_tenant_message_quota(integer,text,text,text,text,text,timestamptz)', 'EXECUTE');
    SELECT NOT has_function_privilege('authenticated', 'public.reserve_tenant_message_quota(integer,text,text,text,text,text,timestamptz)', 'EXECUTE');
    SELECT has_function_privilege('service_role', 'public.finalize_tenant_message_quota_turn(text,text,jsonb,jsonb,timestamptz)', 'EXECUTE');
    SELECT NOT has_function_privilege('authenticated', 'public.finalize_tenant_message_quota_turn(text,text,jsonb,jsonb,timestamptz)', 'EXECUTE');
    SELECT proconfig = ARRAY['search_path=pg_catalog, public'] FROM pg_proc WHERE oid = 'public.reserve_tenant_message_quota(integer,text,text,text,text,text,timestamptz)'::regprocedure;
    SELECT pg_get_userbyid(proowner) = 'postgres' FROM pg_proc WHERE oid = 'public.reserve_tenant_message_quota(integer,text,text,text,text,text,timestamptz)'::regprocedure;
    SELECT proconfig = ARRAY['search_path=pg_catalog, public'] FROM pg_proc WHERE oid = 'public.finalize_tenant_message_quota_turn(text,text,jsonb,jsonb,timestamptz)'::regprocedure;
    SELECT pg_get_userbyid(proowner) = 'postgres' FROM pg_proc WHERE oid = 'public.finalize_tenant_message_quota_turn(text,text,jsonb,jsonb,timestamptz)'::regprocedure;
    SELECT proconfig = ARRAY['search_path=pg_catalog, public'] FROM pg_proc WHERE oid = 'public.finalize_tenant_message_quota_turn(text,text,jsonb,timestamptz)'::regprocedure;
    SELECT pg_get_userbyid(proowner) = 'postgres' FROM pg_proc WHERE oid = 'public.finalize_tenant_message_quota_turn(text,text,jsonb,timestamptz)'::regprocedure;")"
  [ "$(printf '%s\n' "$result" | grep -c '^t$')" -eq 27 ] || die "PostgreSQL $pg_version standard-profile/replay/checksum/object/RPC/privilege checks failed: $result"

  docker exec -i -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 <<'SQL'
DO $$
DECLARE
  v_result jsonb;
  v_before bigint;
  v_consumed integer;
  v_reserved integer;
BEGIN
  v_result := public.reserve_tenant_message_quota(1, 'released-retry', 'integration');
  IF v_result->>'status' <> 'reserved' OR (v_result->>'consumed')::integer <> 1 THEN
    RAISE EXCEPTION 'public-only bootstrap failed: %', v_result;
  END IF;
  IF public.reserve_tenant_message_quota(1, 'released-retry', 'integration')->>'status' <> 'already_reserved' THEN
    RAISE EXCEPTION 'reserved idempotency failed';
  END IF;
  PERFORM public.release_tenant_message_quota(1, 'released-retry', 'integration');
  v_result := public.reserve_tenant_message_quota(1, 'released-retry', 'integration');
  IF v_result->>'status' <> 'reserved' THEN RAISE EXCEPTION 'released retry was not reactivated: %', v_result; END IF;
  PERFORM public.release_tenant_message_quota(1, 'released-retry', 'integration');

  PERFORM public.reserve_tenant_message_quota(1, 'atomic-success', 'integration');
  SELECT count(*) INTO v_before FROM public.history;
  v_result := public.finalize_tenant_message_quota_turn(
    'atomic-success', 'integration',
    '[{"idBot":10,"idUser":7,"message":"question","created":"user","metadata":{}},{"idBot":10,"idUser":7,"message":"answer","created":"bot","metadata":{}}]'::jsonb
  );
  IF v_result->>'status' <> 'consumed' OR jsonb_array_length(v_result->'history') <> 1 THEN
    RAISE EXCEPTION 'atomic finalize failed: %', v_result;
  END IF;
  SELECT "consumedMessages", "reservedMessages" INTO v_consumed, v_reserved
  FROM public.tenant_message_quota_periods WHERE "idTenant" = 1;
  IF v_consumed <> 2 OR v_reserved <> 0 OR (SELECT count(*) FROM public.history) <> v_before + 2 THEN
    RAISE EXCEPTION 'atomic finalize counters/history mismatch';
  END IF;
  v_result := public.finalize_tenant_message_quota_turn(
    'atomic-success', 'integration',
    '[{"idBot":10,"idUser":7,"message":"question","created":"user"},{"idBot":10,"idUser":7,"message":"answer","created":"bot"}]'::jsonb
  );
  IF v_result->>'status' <> 'already_consumed' OR (SELECT count(*) FROM public.history) <> v_before + 2 THEN
    RAISE EXCEPTION 'finalize idempotency failed: %', v_result;
  END IF;

  PERFORM public.reserve_tenant_message_quota(1, 'expired-finalize', 'integration', now() - interval '20 minutes');
  v_result := public.finalize_tenant_message_quota_turn(
    'expired-finalize', 'integration',
    '[{"idBot":10,"idUser":8,"message":"old question","created":"user"},{"idBot":10,"idUser":8,"message":"old answer","created":"bot"}]'::jsonb
  );
  IF v_result->>'status' <> 'already_released' THEN RAISE EXCEPTION 'expired reservation was not reclaimed: %', v_result; END IF;

  PERFORM public.reserve_tenant_message_quota(1, 'cross-period', 'integration');
  IF public.reserve_tenant_message_quota(1, 'cross-period', 'integration', now() + interval '2 months')->>'status' <> 'request_id_reused' THEN
    RAISE EXCEPTION 'cross-period request ID reuse was accepted';
  END IF;
  PERFORM public.release_tenant_message_quota(1, 'cross-period', 'integration');

  UPDATE public.tenant_plans SET "maxMessages" = 2 WHERE "idTenant" = 1;
  v_result := public.reserve_tenant_message_quota(1, 'released-retry', 'integration');
  IF v_result->>'status' <> 'exhausted' OR (SELECT status FROM public.tenant_message_quota_reservations WHERE "idTenant" = 1 AND source = 'integration' AND "requestId" = 'released-retry') <> 'released' THEN
    RAISE EXCEPTION 'released retry bypassed capacity: %', v_result;
  END IF;
  UPDATE public.tenant_plans SET "maxMessages" = 100 WHERE "idTenant" = 1;

  PERFORM public.reserve_tenant_message_quota(1, 'atomic-rollback', 'integration');
END;
$$;
SQL

  if rollback_error="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -c "SELECT public.finalize_tenant_message_quota_turn('atomic-rollback', 'integration', '[{\"idBot\":10,\"idUser\":9,\"message\":\"question\",\"created\":\"user\"},{\"idBot\":10,\"idUser\":9,\"message\":\"reject\",\"created\":\"bot\"}]'::jsonb);" 2>&1)"; then
    die "PostgreSQL $pg_version atomic finalize rollback scenario succeeded"
  fi
  [[ "$rollback_error" == *'history_message_not_reject'* ]] || die "PostgreSQL $pg_version finalize failure was unclear"
  rollback_state="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "
    SELECT status = 'reserved' FROM public.tenant_message_quota_reservations WHERE \"idTenant\" = 1 AND source = 'integration' AND \"requestId\" = 'atomic-rollback';
    SELECT \"reservedMessages\" = 1 AND \"consumedMessages\" = 2 FROM public.tenant_message_quota_periods WHERE \"idTenant\" = 1;
    SELECT count(*) = 0 FROM public.history WHERE message = 'reject';")"
  [ "$(printf '%s\n' "$rollback_state" | grep -c '^t$')" -eq 3 ] || die "PostgreSQL $pg_version finalize did not roll back atomically: $rollback_state"

  docker exec -i -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 <<'SQL'
DO $$
DECLARE
  v_result jsonb;
  v_response jsonb;
  v_replayed jsonb;
  v_consumed integer;
  v_reserved integer;
  v_history_count bigint;
BEGIN
  v_result := public.reserve_tenant_message_quota(
    1, 'replay-exact', '10', '42', repeat('a', 64), 'integration', now()
  );
  IF v_result->>'status' <> 'reserved' THEN RAISE EXCEPTION 'replay-aware reserve failed: %', v_result; END IF;
  v_result := public.finalize_tenant_message_quota_turn(
    'replay-exact', 'integration',
    '[{"idBot":10,"idUser":42,"message":"replay question","created":"user"},{"idBot":10,"idUser":42,"message":"replay answer","created":"bot"}]'::jsonb,
    '{"ok":true,"text":"stored response"}'::jsonb, now()
  );
  IF v_result->>'status' <> 'consumed' OR v_result->'response'->>'text' <> 'stored response'
     OR jsonb_array_length(v_result->'history') <> 1 THEN
    RAISE EXCEPTION 'replay-aware finalize failed: %', v_result;
  END IF;
  SELECT "consumedMessages", "reservedMessages" INTO v_consumed, v_reserved
  FROM public.tenant_message_quota_periods WHERE "idTenant" = 1;
  SELECT count(*) INTO v_history_count FROM public.history;
  v_replayed := public.reserve_tenant_message_quota(
    1, 'replay-exact', '10', '42', repeat('a', 64), 'integration', now()
  );
  IF v_replayed->>'status' <> 'already_consumed'
     OR v_replayed->'response' IS DISTINCT FROM v_result->'response'
     OR jsonb_array_length(v_replayed->'history') <> 1 THEN
    RAISE EXCEPTION 'same replay identity did not return stored response: %', v_replayed;
  END IF;
  IF (SELECT "consumedMessages" FROM public.tenant_message_quota_periods WHERE "idTenant" = 1) <> v_consumed
     OR (SELECT "reservedMessages" FROM public.tenant_message_quota_periods WHERE "idTenant" = 1) <> v_reserved
     OR (SELECT count(*) FROM public.history) <> v_history_count THEN
    RAISE EXCEPTION 'same replay identity caused an extra state transition';
  END IF;
  IF public.reserve_tenant_message_quota(
       1, 'replay-exact', '10', '42', repeat('b', 64), 'integration', now()
     )->>'status' <> 'identity_mismatch' THEN
    RAISE EXCEPTION 'reserve identity mismatch was accepted';
  END IF;
  IF public.finalize_tenant_message_quota_turn(
       'replay-exact', 'integration',
       '[{"idBot":10,"idUser":99,"message":"question","created":"user"},{"idBot":10,"idUser":99,"message":"answer","created":"bot"}]'::jsonb,
       '{"ok":true}'::jsonb, now()
     )->>'status' <> 'identity_mismatch' THEN
    RAISE EXCEPTION 'finalize identity mismatch was accepted';
  END IF;

  IF public.reserve_tenant_message_quota(
       1, 'pre-replay', '10', '1', repeat('c', 64), 'integration', now()
     )->>'status' <> 'legacy_unreplayable' THEN
    RAISE EXCEPTION 'pre-migration reservation was treated as replayable';
  END IF;
  IF public.finalize_tenant_message_quota_turn(
       'pre-replay', 'integration',
       '[{"idBot":10,"idUser":1,"message":"question","created":"user"},{"idBot":10,"idUser":1,"message":"answer","created":"bot"}]'::jsonb,
       '{"ok":true}'::jsonb, now()
     )->>'status' <> 'legacy_unreplayable' THEN
    RAISE EXCEPTION 'legacy finalization was treated as replayable';
  END IF;

  v_result := public.reserve_tenant_message_quota(
    1, 'oversized-replay', '10', '43', repeat('d', 64), 'integration', now()
  );
  IF v_result->>'status' <> 'reserved' THEN RAISE EXCEPTION 'oversized replay reserve failed: %', v_result; END IF;
  v_result := public.finalize_tenant_message_quota_turn(
    'oversized-replay', 'integration',
    '[{"idBot":10,"idUser":43,"message":"large question","created":"user"},{"idBot":10,"idUser":43,"message":"large answer","created":"bot"}]'::jsonb,
    jsonb_build_object('ok', true, 'text', repeat('t', 9000), 'payload', repeat('x', 300000)), now()
  );
  v_response := v_result->'response';
  IF v_result->>'status' <> 'consumed' OR v_response->>'type' <> 'degraded'
     OR (v_response->>'replayTruncated')::boolean IS NOT TRUE
     OR octet_length(v_response->>'text') <> 8192
     OR v_response ? 'payload'
     OR pg_column_size(v_response) > 262144 THEN
    RAISE EXCEPTION 'oversized replay did not use bounded fallback: %', v_result;
  END IF;
  v_replayed := public.reserve_tenant_message_quota(
    1, 'oversized-replay', '10', '43', repeat('d', 64), 'integration', now()
  );
  IF v_replayed->>'status' <> 'already_consumed' OR v_replayed->'response' IS DISTINCT FROM v_response THEN
    RAISE EXCEPTION 'bounded fallback was not deterministic on replay: %', v_replayed;
  END IF;

  v_result := public.reserve_tenant_message_quota(
    1, 'mixed-new-old', '10', '44', repeat('e', 64), 'integration', now()
  );
  IF v_result->>'status' <> 'reserved' THEN RAISE EXCEPTION 'new reserve for old finalizer failed: %', v_result; END IF;
  v_result := public.finalize_tenant_message_quota_turn(
    'mixed-new-old', 'integration',
    '[{"idBot":10,"idUser":44,"message":"mixed question","created":"user"},{"idBot":10,"idUser":44,"message":"mixed answer","created":"bot"}]'::jsonb,
    now()
  );
  IF v_result->>'status' <> 'consumed' THEN RAISE EXCEPTION 'historical finalizer rejected new reservation: %', v_result; END IF;
  v_result := public.reserve_tenant_message_quota(1, 'mixed-old-new', 'integration', now());
  IF v_result->>'status' <> 'reserved' THEN RAISE EXCEPTION 'historical reserve failed after replay migration: %', v_result; END IF;
  IF public.reserve_tenant_message_quota(
       1, 'mixed-old-new', '10', '45', repeat('f', 64), 'integration', now()
     )->>'status' <> 'legacy_unreplayable' THEN
    RAISE EXCEPTION 'historical reservation was incorrectly upgraded to replayable';
  END IF;
END;
$$;
SQL
  printf 'PASS: PostgreSQL %s replay-aware overload/idempotency/identity/bounds/compatibility checks\n' "$pg_version"

  provisioned="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "
    SELECT private.provision_known_studio_mapping() = 'provisioned';
    SELECT count(*) = 1 FROM public.tenant_studio_organization_mappings;
    SELECT count(*) = 1 FROM public.tenant_studio_workspace_mappings;")"
  [ "$(printf '%s\n' "$provisioned" | grep -c '^t$')" -eq 3 ] || die "PostgreSQL $pg_version known mapping is not idempotent"

  custom="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "BEGIN;
    DELETE FROM public.tenant_studio_workspace_mappings; DELETE FROM public.tenant_studio_organization_mappings;
    DELETE FROM public.tenant_plans; DELETE FROM public.tenants; DELETE FROM studio.workspace; DELETE FROM studio.organization;
    SELECT private.provision_known_studio_mapping() = 'skipped_custom'; ROLLBACK;")"
  [ "$custom" = t ] || die "PostgreSQL $pg_version custom seed-free install did not skip provisioning"

  if partial_error="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -c "BEGIN; DELETE FROM studio.workspace; SELECT private.provision_known_studio_mapping();" 2>&1)"; then
    die "PostgreSQL $pg_version partial seed set did not fail"
  fi
  [[ "$partial_error" == *'partial expected seed objects'* ]] || die "PostgreSQL $pg_version partial seed failure was unclear"
  if conflict_error="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -c "BEGIN; INSERT INTO public.tenants VALUES (2); DELETE FROM public.tenant_studio_workspace_mappings; DELETE FROM public.tenant_studio_organization_mappings; INSERT INTO public.tenant_studio_organization_mappings VALUES (2, 'ca2a7ece-14c6-458c-9266-5c3d96e547f2'); SELECT private.provision_known_studio_mapping();" 2>&1)"; then
    die "PostgreSQL $pg_version conflicting known mapping did not fail"
  fi
  [[ "$conflict_error" == *'Conflicting fixed Studio organization mapping'* ]] || die "PostgreSQL $pg_version mapping conflict failure was unclear"

  docker exec -i -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 <<'SQL' >/dev/null
INSERT INTO public.tenants VALUES
  (2, '{"created_by":"qa","domain":"example.test"}'),
  (3, '{"secretSeed":"  ","teamsSecret":"valid-teams"}'),
  (4, '{"secretSeed":"valid-seed","teamsSecret":"  "}');
SQL
  docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -c "$(command cat "$ROOT_DIR/volumes/db/daiana-migrations/20260805120000_backfill_tenant_secrets.sql")" >/dev/null
  tenant_secret_result="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "
    SELECT settings->>'secretSeed' ~ '^[0-9a-f-]{36}$' AND settings->>'teamsSecret' = 'waHW4b2Kfe_OoYXxnSUscqIMuESvQhunKt6deG1uXyU=' FROM public.tenants WHERE \"idTenant\" = 1;
    SELECT settings ? 'secretSeed' AND settings->>'teamsSecret' = 'waHW4b2Kfe_OoYXxnSUscqIMuESvQhunKt6deG1uXyU=' FROM public.tenants WHERE \"idTenant\" = 2;
    SELECT settings->>'secretSeed' <> '' AND settings->>'teamsSecret' = 'valid-teams' FROM public.tenants WHERE \"idTenant\" = 3;
    SELECT settings->>'secretSeed' = 'valid-seed' AND settings->>'teamsSecret' = 'waHW4b2Kfe_OoYXxnSUscqIMuESvQhunKt6deG1uXyU=' FROM public.tenants WHERE \"idTenant\" = 4;
    SELECT count(*) = 4 FROM public.tenants WHERE settings ? 'secretSeed' AND settings ? 'teamsSecret';")"
  [ "$(printf '%s\n' "$tenant_secret_result" | grep -c '^t$')" -eq 5 ] || die "tenant secret backfill/default/non-overwrite checks failed"
  tenant_seed_before="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "SELECT settings->>'secretSeed' FROM public.tenants WHERE \"idTenant\" = 2;")"
  docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 -c "$(command cat "$ROOT_DIR/volumes/db/daiana-migrations/20260805120000_backfill_tenant_secrets.sql")" >/dev/null
  tenant_seed_after="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "SELECT settings->>'secretSeed' FROM public.tenants WHERE \"idTenant\" = 2;")"
  [ "$tenant_seed_before" = "$tenant_seed_after" ] || die "tenant secret backfill is not idempotent"
  printf 'PASS: PostgreSQL %s tenant secret backfill randomness/default/non-overwrite/idempotency checks\n' "$pg_version"

  cp "$ROOT_DIR/volumes/db/daiana-migrations/20260717120000_add_shared_message_quota.sql" "$drift_dir/20260717120000_add_shared_message_quota.sql"
  printf '\n-- checksum drift test\n' >> "$drift_dir/20260717120000_add_shared_message_quota.sql"
  DAIANA_MIGRATIONS_DIR="$drift_dir"
  export DAIANA_MIGRATIONS_DIR
  if run_daiana_migrations; then die "PostgreSQL $pg_version checksum drift was accepted"; fi
  count="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc 'SELECT count(*) FROM private.daiana_installer_schema_migrations;')"
  [ "$count" = 3 ] || die "PostgreSQL $pg_version drift changed history"

  rm -f "$drift_dir/20260717120000_add_shared_message_quota.sql"
  printf 'CREATE TABLE public.must_rollback(id integer);\nSELECT 1/0;\n' > "$drift_dir/20260717130000_failure.sql"
  if run_daiana_migrations; then die "PostgreSQL $pg_version failing migration succeeded"; fi
  recorded="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "SELECT count(*) FROM private.daiana_installer_schema_migrations WHERE version = '20260717130000';")"
  table_exists="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "SELECT to_regclass('public.must_rollback') IS NOT NULL;")"
  [ "$recorded" = 0 ] && [ "$table_exists" = f ] || die "PostgreSQL $pg_version failed migration was not atomic"

  printf 'PASS: PostgreSQL %s standard-profile/apply/replay/drift/failure/quota/finalize/privilege/RPC checks\n' "$pg_version"
  cleanup
  trap - EXIT INT TERM
done
