#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PACKAGE="$ROOT_DIR/dmo-manual-compat"
VERSIONS="${DMO_MANUAL_COMPAT_TEST_PG_VERSIONS:-15 17}"
command -v docker >/dev/null 2>&1 || { printf 'SKIP: docker is required\n'; exit 0; }
docker info >/dev/null 2>&1 || { printf 'SKIP: Docker daemon is unavailable\n'; exit 0; }

fail() { printf 'FAIL: %s\n' "$*" >&2; exit 1; }

for version in $VERSIONS; do
  case "$version" in 15|17) ;; *) fail "unsupported PostgreSQL version: $version" ;; esac
  for studio_schema in studio daianastudio; do
    container="dmo-manual-compat-pg${version}-${studio_schema}-$$"
    work_dir="$(mktemp -d)"
    cleanup() { docker rm -f "$container" >/dev/null 2>&1 || true; rm -rf "$work_dir"; }
    trap cleanup EXIT INT TERM
    docker run --rm -d --name "$container" -p 127.0.0.1::5432 -e POSTGRES_PASSWORD=test-password "postgres:${version}-alpine" >/dev/null
    for _ in $(seq 1 30); do docker exec "$container" pg_isready -U postgres >/dev/null 2>&1 && break; sleep 1; done
    docker exec "$container" pg_isready -U postgres >/dev/null 2>&1 || fail "PostgreSQL $version did not start"
    docker exec -i -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 <<SQL
CREATE ROLE anon NOLOGIN; CREATE ROLE authenticated NOLOGIN; CREATE ROLE service_role NOLOGIN; CREATE ROLE studio_owner NOLOGIN;
CREATE SCHEMA private; CREATE SCHEMA daianawebui AUTHORIZATION studio_owner; CREATE TABLE daianawebui.marker (id integer PRIMARY KEY);
CREATE SCHEMA $studio_schema AUTHORIZATION studio_owner;
CREATE TABLE $studio_schema.organization (id uuid PRIMARY KEY, name text NOT NULL);
CREATE TABLE $studio_schema.workspace (id uuid PRIMARY KEY, "organizationId" uuid NOT NULL, name text NOT NULL);
CREATE TABLE public.tenants ("idTenant" integer PRIMARY KEY, settings jsonb);
CREATE TABLE public.tenant_plans (id integer PRIMARY KEY, "idTenant" integer NOT NULL, "planName" text NOT NULL, "maxMessages" integer, "studioIntegrated" boolean, "periodStartAt" timestamptz NOT NULL, "expiresAt" timestamptz, "validatedAt" timestamptz, status text NOT NULL, "createdAt" timestamptz, "updatedAt" timestamptz);
CREATE TABLE public.aibot ("idBot" integer PRIMARY KEY, "idTenant" integer NOT NULL, botpublic boolean NOT NULL);
CREATE TABLE public.history (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "idBot" integer NOT NULL, "idUser" integer, message text NOT NULL, created text, metadata jsonb, dataframe jsonb, "createdAt" timestamptz NOT NULL DEFAULT now());
INSERT INTO public.tenants VALUES (1, '{}'::jsonb); INSERT INTO public.tenant_plans VALUES (1, 1, 'synthetic', 10, true, now(), now() + interval '1 year', now(), 'active', now(), now()); INSERT INTO public.aibot VALUES (1, 1, true); INSERT INTO public.history ("idBot", "idUser", message, created) VALUES (1, 1, 'synthetic', 'bot');
SQL
    backup="$work_dir/backup.dump"; printf 'synthetic backup\n' > "$backup"; backup_hash="$(shasum -a 256 "$backup" | awk '{print $1}')"
    port="$(docker port "$container" 5432/tcp | awk -F: '{print $2}')"
    export PGHOST=127.0.0.1 PGPORT="$port" PGUSER=postgres PGDATABASE=postgres PGPASSWORD=test-password
    before="$(psql -X -qAt -c "SELECT md5(string_agg(attname, ',' ORDER BY attname)) FROM pg_attribute WHERE attrelid = 'daianawebui.marker'::regclass AND attnum > 0")"
    "$PACKAGE/bin/dmo-manual-compat" preflight
    [ "$(psql -X -qAt -c "SELECT to_regclass('public.tenant_message_quota_periods') IS NULL")" = t ] || fail 'preflight mutated quota objects'
    psql -X -q -c 'CREATE TABLE public.tenant_message_quota_periods (id integer PRIMARY KEY)'
    if "$PACKAGE/bin/dmo-manual-compat" plan >/dev/null 2>&1; then fail 'partial manual footprint was accepted'; fi
    [ "$(psql -X -qAt -c "SELECT to_regclass('public.figure_artifacts') IS NULL")" = t ] || fail 'partial footprint reached later DDL'
    psql -X -q -c 'DROP TABLE public.tenant_message_quota_periods'
    "$PACKAGE/bin/dmo-manual-compat" apply --backup-file "$backup" --backup-sha256 "$backup_hash"
    "$PACKAGE/bin/dmo-manual-compat" plan | grep -c '^SKIP ' | grep -qx 6 || fail 'rerun did not skip all six operations'
    after="$(psql -X -qAt -c "SELECT md5(string_agg(attname, ',' ORDER BY attname)) FROM pg_attribute WHERE attrelid = 'daianawebui.marker'::regclass AND attnum > 0")"
    [ "$before" = "$after" ] || fail 'WebUI changed'
    psql -X -qAt -c "SELECT count(*) = 0 FROM public.tenant_studio_organization_mappings; SELECT count(*) = 0 FROM public.tenant_studio_workspace_mappings; SELECT to_regprocedure('public.list_studio_mapping_catalog()') IS NOT NULL;" | grep -c '^t$' | grep -qx 3 || fail 'explicit mapping or catalog contract failed'
    cleanup; trap - EXIT INT TERM
  done
done

tamper_dir="$(mktemp -d)"; trap 'rm -rf "$tamper_dir"' EXIT
cp -R "$PACKAGE" "$tamper_dir/package"
printf '\n-- tampered\n' >> "$tamper_dir/package/sql/20260731120000_add_flowise_quota_finalization.sql"
if "$tamper_dir/package/bin/dmo-manual-compat" preflight >/dev/null 2>&1; then fail 'tampered manifest was accepted'; fi
printf 'PASS: DMO manual package validates synthetic PostgreSQL 15/17, both Studio variants, idempotency, WebUI immutability, and manifest tampering\n'
