#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSIONS="${DAIANA_MIGRATION_TEST_PG_VERSIONS:-}"

if [ -z "$VERSIONS" ]; then
  printf 'SKIP: set DAIANA_MIGRATION_TEST_PG_VERSIONS="15 17" to run private-chat migration tests\n'
  exit 0
fi
command -v docker >/dev/null 2>&1 || { printf 'FAIL: docker is required\n' >&2; exit 1; }
docker info >/dev/null 2>&1 || { printf 'FAIL: Docker daemon is unavailable\n' >&2; exit 1; }

die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
log() { printf '===> %s\n' "$*" >&2; }
docker_cmd() { docker "$@"; }
# shellcheck disable=SC1091
source "$ROOT_DIR/utils/daiana-migrations.sh"

for pg_version in $VERSIONS; do
  case "$pg_version" in 15|17) ;; *) die "unsupported PostgreSQL version: $pg_version" ;; esac
  container="daiana-private-chat-pg${pg_version}-$$"
  work_dir="$(mktemp -d)"
  cleanup() { docker rm -f "$container" >/dev/null 2>&1 || true; rm -rf "$work_dir"; }
  trap cleanup EXIT INT TERM
  docker run --rm -d --name "$container" -e POSTGRES_PASSWORD=test-password "postgres:${pg_version}-alpine" >/dev/null
  ready=0
  for _attempt in $(seq 1 30); do
    docker exec "$container" pg_isready -U postgres >/dev/null 2>&1 && { ready=1; break; }
    sleep 1
  done
  [ "$ready" -eq 1 ] || die "PostgreSQL $pg_version did not become ready"

  docker exec -i -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 <<'SQL'
CREATE ROLE anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE service_role NOLOGIN;
CREATE TABLE public.history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idBot" integer NOT NULL,
  "idUser" integer,
  message text NOT NULL,
  created text,
  metadata jsonb,
  dataframe jsonb,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.aibot ("idBot" integer PRIMARY KEY, "idTenant" integer NOT NULL);
CREATE TABLE public.tenant_message_quota_reservations (
  "idTenant" integer NOT NULL, source text NOT NULL, "requestId" text NOT NULL,
  result jsonb NOT NULL DEFAULT '{}'::jsonb, status text NOT NULL,
  "consumedAt" timestamptz, "periodStartAt" timestamptz NOT NULL,
  PRIMARY KEY ("idTenant", source, "requestId")
);
CREATE TABLE public.tenant_message_quota_periods (
  "idTenant" integer NOT NULL, "periodStartAt" timestamptz NOT NULL,
  "reservedMessages" integer NOT NULL DEFAULT 0,
  "consumedMessages" integer NOT NULL DEFAULT 0,
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("idTenant", "periodStartAt")
);
CREATE FUNCTION public.reconcile_tenant_message_quota_reservations(integer, timestamptz)
RETURNS void LANGUAGE sql AS $$ SELECT; $$;
INSERT INTO public.history ("idBot", "idUser", message, created) VALUES (1, 2, 'seed', 'bot');
SQL

  migration_dir="$work_dir/migrations"
  mkdir -p "$migration_dir"
  cp "$ROOT_DIR/volumes/db/daiana-migrations/20260731120000_add_flowise_quota_finalization.sql" "$migration_dir/"
  cp "$ROOT_DIR/volumes/db/daiana-migrations/20260727130000_add_history_message_refs.sql" "$migration_dir/"
  cp "$ROOT_DIR/volumes/db/daiana-migrations/20260727140000_allow_authorized_private_message_quota.sql" "$migration_dir/"
  export POSTGRES_PASSWORD=test-password POSTGRES_DB=postgres DAIANA_DB_CONTAINER="$container" DAIANA_MIGRATIONS_DIR="$migration_dir"
  run_daiana_migrations
  run_daiana_migrations
  checks="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "
    SELECT count(*) = 1 FROM public.history WHERE message_ref IS NOT NULL;
    SELECT to_regclass('public.figure_artifacts') IS NOT NULL;
    SELECT has_table_privilege('service_role', 'public.figure_artifacts', 'SELECT');
    SELECT has_function_privilege('service_role', 'public.finalize_tenant_message_quota_turn(text,text,jsonb,jsonb,timestamptz)', 'EXECUTE');
     SELECT NOT has_function_privilege('authenticated', 'public.finalize_tenant_message_quota_turn(text,text,jsonb,jsonb,timestamptz)', 'EXECUTE');
     SELECT has_function_privilege('service_role', 'public.finalize_tenant_message_quota_without_history(text,text,jsonb,timestamptz)', 'EXECUTE');
     SELECT NOT has_function_privilege('authenticated', 'public.finalize_tenant_message_quota_without_history(text,text,jsonb,timestamptz)', 'EXECUTE');")"
  [ "$(printf '%s\n' "$checks" | grep -c '^t$')" -eq 7 ] \
    || die "PostgreSQL $pg_version feature migration checks failed: $checks"
  printf 'PASS: PostgreSQL %s feature migrations applied, skipped idempotently, and hardened privileges\n' "$pg_version"
  cleanup
  trap - EXIT INT TERM
done
