#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
command -v docker >/dev/null 2>&1 || { printf 'SKIP: docker is required\n'; exit 0; }
docker info >/dev/null 2>&1 || { printf 'SKIP: Docker daemon is unavailable\n'; exit 0; }

container="daiana-legacy-profile-pg15-$$"
cleanup() { docker rm -f "$container" >/dev/null 2>&1 || true; }
trap cleanup EXIT INT TERM
docker run --rm -d --name "$container" -e POSTGRES_PASSWORD=test-password postgres:15-alpine >/dev/null
for _ in $(seq 1 30); do docker exec "$container" pg_isready -U postgres >/dev/null 2>&1 && break; sleep 1; done
docker exec "$container" pg_isready -U postgres >/dev/null 2>&1 || { printf 'FAIL: PostgreSQL 15 did not become ready\n' >&2; exit 1; }

docker exec -i -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -v ON_ERROR_STOP=1 <<'SQL'
CREATE ROLE anon NOLOGIN; CREATE ROLE authenticated NOLOGIN; CREATE ROLE service_role NOLOGIN; CREATE ROLE studio NOLOGIN;
CREATE SCHEMA private AUTHORIZATION postgres;
CREATE TABLE public.tenants ("idTenant" integer PRIMARY KEY, settings jsonb);
CREATE TABLE public.tenant_plans (id integer PRIMARY KEY, "idTenant" integer NOT NULL, "planName" text NOT NULL, "maxMessages" integer, "studioIntegrated" boolean, "periodStartAt" timestamptz NOT NULL, "expiresAt" timestamptz, "validatedAt" timestamptz, status text NOT NULL, "createdAt" timestamptz, "updatedAt" timestamptz);
CREATE TABLE public.aibot ("idBot" integer PRIMARY KEY, "idTenant" integer NOT NULL, botpublic boolean NOT NULL);
CREATE TABLE public.history (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "idBot" integer NOT NULL, "idUser" integer, message text NOT NULL, created text, metadata jsonb, dataframe jsonb, "createdAt" timestamptz NOT NULL DEFAULT now());
CREATE SCHEMA daianastudio AUTHORIZATION studio;
CREATE TABLE daianastudio.organization (id uuid PRIMARY KEY, name text NOT NULL);
CREATE TABLE daianastudio.workspace (id uuid PRIMARY KEY, "organizationId" uuid NOT NULL, name text NOT NULL);
CREATE SCHEMA daianawebui AUTHORIZATION studio;
CREATE TABLE daianawebui.webui_marker (id integer PRIMARY KEY);
INSERT INTO public.tenants VALUES (1, '{}');
INSERT INTO public.tenant_plans VALUES (1, 1, 'studio', 10, true, now(), now() + interval '1 year', now(), 'active', now(), now());
INSERT INTO public.aibot VALUES (10, 1, true);
INSERT INTO public.history ("idBot", "idUser", message, created) VALUES (10, 1, 'synthetic history', 'bot');
INSERT INTO daianastudio.organization VALUES ('11111111-1111-1111-1111-111111111111', 'Synthetic organization');
INSERT INTO daianastudio.workspace VALUES ('22222222-2222-2222-2222-222222222222', '11111111-1111-1111-1111-111111111111', 'Synthetic workspace');
SQL

cd "$ROOT_DIR"
log() { printf '===> %s\n' "$*" >&2; }; die() { printf 'FAIL: %s\n' "$*" >&2; return 1; }; docker_cmd() { command docker "$@"; }
# shellcheck disable=SC1091
source utils/daiana-migrations.sh
POSTGRES_PASSWORD=test-password POSTGRES_DB=postgres DAIANA_DB_CONTAINER="$container" DAIANA_MIGRATION_PROFILE=legacy-daianastudio run_daiana_migrations
POSTGRES_PASSWORD=test-password POSTGRES_DB=postgres DAIANA_DB_CONTAINER="$container" DAIANA_MIGRATION_PROFILE=legacy-daianastudio run_daiana_migrations

switch_dir="$(mktemp -d)"
trap 'rm -rf "$switch_dir"; cleanup' EXIT INT TERM
printf 'CREATE TABLE public.profile_switch_ddl(id integer);\n' > "$switch_dir/20260901000000_profile_switch_ddl.sql"
if switch_error="$(POSTGRES_PASSWORD=test-password POSTGRES_DB=postgres DAIANA_DB_CONTAINER="$container" DAIANA_MIGRATIONS_DIR="$switch_dir" DAIANA_MIGRATION_PROFILE=standard DAIANA_MIGRATION_LEDGER=private.daiana_installer_schema_migrations run_daiana_migrations 2>&1)"; then
  printf 'FAIL: standard profile was accepted after legacy migrations\n' >&2
  exit 1
fi
[[ "$switch_error" == *'profile interlock'*'refusing standard before DDL'* ]] || { printf 'FAIL: profile switch error was unclear: %s\n' "$switch_error" >&2; exit 1; }

result="$(docker exec -e PGPASSWORD=test-password "$container" psql -U postgres -d postgres -Atqc "
SELECT to_regnamespace('daianastudio') IS NOT NULL AND to_regnamespace('studio') IS NULL;
SELECT to_regnamespace('daianawebui') IS NOT NULL AND to_regclass('daianawebui.webui_marker') IS NOT NULL;
SELECT count(*) = 0 FROM public.tenant_studio_organization_mappings;
SELECT count(*) = 0 FROM public.tenant_studio_workspace_mappings;
SELECT count(*) = 6 FROM private.daiana_legacy_daianastudio_schema_migrations;
SELECT NOT EXISTS (SELECT 1 FROM private.daiana_legacy_daianastudio_schema_migrations WHERE version = '20260805120000');
SELECT settings = '{}'::jsonb FROM public.tenants WHERE \"idTenant\" = 1;
SELECT to_regclass('public.profile_switch_ddl') IS NULL;
SELECT to_regclass('private.daiana_installer_schema_migrations') IS NULL;
SELECT count(*) = 1
   AND min(\"organizationId\") = '11111111-1111-1111-1111-111111111111'
   AND min(\"workspaceId\") = '22222222-2222-2222-2222-222222222222'
FROM public.list_studio_mapping_catalog();
SELECT count(*) = 1 FROM public.history WHERE message_ref IS NOT NULL;")"
[ "$(printf '%s\n' "$result" | grep -c '^t$')" -eq 11 ] || { printf 'FAIL: legacy profile assertions failed: %s\n' "$result" >&2; exit 1; }
printf 'PASS: PostgreSQL 15 synthetic legacy profile preserves schemas/WebUI state, skips runtime secrets, and rejects profile switches before DDL\n'
